#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

DATASET_NAME="simplevqa"
RUN_ID="${RUN_ID:-oop5_simplevqa_cztools_$(date +%Y%m%d_%H%M%S)}"
BASE_DIR="/inspire/qb-ilm2/project/26summer-camp-01/26210500/benchmark_runs/${RUN_ID}"

export RUN_ID
export DATASET="${DATASET:-$DATASET_NAME}"
export DATASET_ROOT="${DATASET_ROOT:-/inspire/qb-ilm2/project/26summer-camp-01/26210500/datasets}"
export OUTPUT="${OUTPUT:-${BASE_DIR}/predictions.jsonl}"
export TRAJ_DIR="${TRAJ_DIR:-${BASE_DIR}/trajectories}"
export SUBMISSION_DIR="${SUBMISSION_DIR:-${BASE_DIR}/submission}"
export JUDGE_OUTPUT="${JUDGE_OUTPUT:-${OUTPUT}.judge.jsonl}"

# Same CZ-like test configuration as the current OOP5 benchmark runs.
export WORKERS="${WORKERS:-10}"
export LIMIT="${LIMIT:-100}"
export START="${START:-0}"
export MAX_STEPS="${MAX_STEPS:-20}"

export MAX_TOKENS="${MAX_TOKENS:-16000}"
export TEMPERATURE="${TEMPERATURE:-1.0}"
export CZ_SAMPLING_COMPAT="${CZ_SAMPLING_COMPAT:-1}"

export CASE_REFLECTION_ATTEMPTS="${CASE_REFLECTION_ATTEMPTS:-0}"
export MIN_MODEL_ATTEMPTS="${MIN_MODEL_ATTEMPTS:-1}"
export FORCED_ANSWER_ENABLED="${FORCED_ANSWER_ENABLED:-1}"
export FINAL_ANSWER_MAX_ATTEMPTS="${FINAL_ANSWER_MAX_ATTEMPTS:-10}"

export SEARCH_TEXT_DEFAULT_FETCH="${SEARCH_TEXT_DEFAULT_FETCH:-1}"
export SEARCH_IMAGE_DEFAULT_FETCH="${SEARCH_IMAGE_DEFAULT_FETCH:-1}"
export SEARCH_TEXT_MAX_CHARS="${SEARCH_TEXT_MAX_CHARS:-500}"
export SEARCH_TEXT_MAX_TOP_K="${SEARCH_TEXT_MAX_TOP_K:-10}"
export DISABLE_BROWSER_TOOLS="${DISABLE_BROWSER_TOOLS:-0}"
export SEARCH_TOOL_MAX_CONCURRENCY="${SEARCH_TOOL_MAX_CONCURRENCY:-2}"
export BROWSER_TOOL_MAX_CONCURRENCY="${BROWSER_TOOL_MAX_CONCURRENCY:-2}"
export PRE_TOOL_ANSWER_GATE_ENABLED="${PRE_TOOL_ANSWER_GATE_ENABLED:-0}"
export SEARCH_NOVELTY_GUARD_ENABLED="${SEARCH_NOVELTY_GUARD_ENABLED:-0}"

export REFLECTION_ENABLED="${REFLECTION_ENABLED:-1}"
export REFLECTION_MODEL_ENABLED="${REFLECTION_MODEL_ENABLED:-1}"
export SEARCH_CHAIN_REFLECTION_ENABLED="${SEARCH_CHAIN_REFLECTION_ENABLED:-1}"
export MEMORY_MODEL_ENABLED="${MEMORY_MODEL_ENABLED:-1}"
export CASE_MEMORY_ENABLED="${CASE_MEMORY_ENABLED:-1}"
export CASE_MEMORY_MODEL_ENABLED="${CASE_MEMORY_MODEL_ENABLED:-1}"
export MEMORY_RETRIEVE_TOP_K="${MEMORY_RETRIEVE_TOP_K:-0}"
export CLIN_MEMORY_WRITE_ENABLED="${CLIN_MEMORY_WRITE_ENABLED:-0}"
export STRATEGY_MEMORY_TOP_K="${STRATEGY_MEMORY_TOP_K:-3}"
export FRESH_MEMORY="${FRESH_MEMORY:-1}"

./run_benchmark.sh
